package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.PrefectureInfrastructure;
import vn.com.vti.springexam.entity.PrefectureInfrastructureExample;

public interface PrefectureInfrastructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    long countByExample(PrefectureInfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int deleteByExample(PrefectureInfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int insert(PrefectureInfrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int insertSelective(PrefectureInfrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    List<PrefectureInfrastructure> selectByExample(PrefectureInfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    PrefectureInfrastructure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int updateByExampleSelective(@Param("row") PrefectureInfrastructure row, @Param("example") PrefectureInfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int updateByExample(@Param("row") PrefectureInfrastructure row, @Param("example") PrefectureInfrastructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int updateByPrimaryKeySelective(PrefectureInfrastructure row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefecture_infrastructure
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    int updateByPrimaryKey(PrefectureInfrastructure row);
}