package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.Section3;
import vn.com.vti.springexam.entity.Section3Example;

public interface Section3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    long countByExample(Section3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int deleteByExample(Section3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int insert(Section3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int insertSelective(Section3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    List<Section3> selectByExample(Section3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    Section3 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int updateByExampleSelective(@Param("row") Section3 row, @Param("example") Section3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int updateByExample(@Param("row") Section3 row, @Param("example") Section3Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int updateByPrimaryKeySelective(Section3 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section3
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    int updateByPrimaryKey(Section3 row);
}