package vn.com.vti.springexam.entity;

public class BusinessType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.business_type_id
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    private String businessTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.business_type_name
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    private String businessTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.business_type_id
     *
     * @return the value of business_type.business_type_id
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    public String getBusinessTypeId() {
        return businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.business_type_id
     *
     * @param businessTypeId the value for business_type.business_type_id
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    public void setBusinessTypeId(String businessTypeId) {
        this.businessTypeId = businessTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.business_type_name
     *
     * @return the value of business_type.business_type_name
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    public String getBusinessTypeName() {
        return businessTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.business_type_name
     *
     * @param businessTypeName the value for business_type.business_type_name
     *
     * @mbg.generated Mon Mar 14 10:44:07 JST 2022
     */
    public void setBusinessTypeName(String businessTypeName) {
        this.businessTypeName = businessTypeName;
    }
}