package vn.com.vti.springexam.entity;

public class Prefecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.name
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.population
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private Integer population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.section8_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private Integer section8Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.section3_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private Integer section3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.is_government_designed_city
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    private Boolean isGovernmentDesignedCity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.id
     *
     * @return the value of prefecture.id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.id
     *
     * @param id the value for prefecture.id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.name
     *
     * @return the value of prefecture.name
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.name
     *
     * @param name the value for prefecture.name
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.population
     *
     * @return the value of prefecture.population
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.population
     *
     * @param population the value for prefecture.population
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.section8_id
     *
     * @return the value of prefecture.section8_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public Integer getSection8Id() {
        return section8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.section8_id
     *
     * @param section8Id the value for prefecture.section8_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setSection8Id(Integer section8Id) {
        this.section8Id = section8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.section3_id
     *
     * @return the value of prefecture.section3_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public Integer getSection3Id() {
        return section3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.section3_id
     *
     * @param section3Id the value for prefecture.section3_id
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setSection3Id(Integer section3Id) {
        this.section3Id = section3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.is_government_designed_city
     *
     * @return the value of prefecture.is_government_designed_city
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public Boolean getIsGovernmentDesignedCity() {
        return isGovernmentDesignedCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.is_government_designed_city
     *
     * @param isGovernmentDesignedCity the value for prefecture.is_government_designed_city
     *
     * @mbg.generated Wed Sep 20 22:35:35 JST 2023
     */
    public void setIsGovernmentDesignedCity(Boolean isGovernmentDesignedCity) {
        this.isGovernmentDesignedCity = isGovernmentDesignedCity;
    }
}