package vn.com.vti.springexam.entity;

public class PrefectureInfrastructure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.infrastructure_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    private Integer infrastructureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.prefecture_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    private Integer prefectureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.id
     *
     * @return the value of prefecture_infrastructure.id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.id
     *
     * @param id the value for prefecture_infrastructure.id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.infrastructure_id
     *
     * @return the value of prefecture_infrastructure.infrastructure_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public Integer getInfrastructureId() {
        return infrastructureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.infrastructure_id
     *
     * @param infrastructureId the value for prefecture_infrastructure.infrastructure_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public void setInfrastructureId(Integer infrastructureId) {
        this.infrastructureId = infrastructureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.prefecture_id
     *
     * @return the value of prefecture_infrastructure.prefecture_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public Integer getPrefectureId() {
        return prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.prefecture_id
     *
     * @param prefectureId the value for prefecture_infrastructure.prefecture_id
     *
     * @mbg.generated Wed Sep 27 22:13:17 JST 2023
     */
    public void setPrefectureId(Integer prefectureId) {
        this.prefectureId = prefectureId;
    }
}