package vn.com.vti.springexam.entity;

public class Section8 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section8.id
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section8.name
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section8.id
     *
     * @return the value of section8.id
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section8.id
     *
     * @param id the value for section8.id
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section8.name
     *
     * @return the value of section8.name
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section8.name
     *
     * @param name the value for section8.name
     *
     * @mbg.generated Wed Sep 27 23:01:52 JST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}